name: Test app

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask pytest

    - name: Run tests
      run: |
        cd src
        pytest --maxfail=1 --disable-warnings -q > app_result.log || true
        cat app_result.log
    - name: upload test result log
      uses: actions/upload-artifact@v4
      with:
        name: pytest-results
        path: src/app_result.log
